### ISSUE TITLE
Caption font size too large

### ISSUE THREAD

**Issue by koppor** [sieversMartin/LNI#10]
The class is missing `\RequirePackage[font=small]{caption}`

Left: result when using the class; right: result with the original template.

![grabbed_20161220-144924](https://cloud.githubusercontent.com/assets/1366654/21352812/8355cfc6-c6c3-11e6-9b45-e4de97891dd4.png)

**Comment by sieversMartin** [comment]
I changed this directly in the definition of `\@makecaption` to avoid the caption package.
