### ISSUE TITLE
PDF properties show footnote too

### ISSUE THREAD

**Issue by koppor** [sieversMartin/LNI#11]
When viewing the PDF properties of a paper, it seems that the footnote is also used as author string.

![grabbed_20161220-145832](https://cloud.githubusercontent.com/assets/1366654/21353118/e1b4f550-c6c4-11e6-9067-1833cfdab634.png)

**Comment by koppor** [comment]
After consulting http://tex.stackexchange.com/a/17254/9075, the solution seems to be to move `\title` and `\author` before `\begin{document}` and inside the `cl`s`:

```
\renewcommand{\title}{\@dblarg\@@title}
\def\@@title[#1]#2{\gdef\@shorttitle{#1}\gdef\@title{#2}%
\ifusehyperref\hypersetup{pdftitle={\@title}}\fi%
}

\renewcommand{\author}{\@dblarg\@@author}
\def\@@author[#1]#2{\gdef\@shortauthor{{\let\footnote\@gobble\def\and{\unskip,\ }#1}}\gdef\@author{#2}%
\ifusehyperref\hypersetup{pdfauthor={\@shortauthor}}\fi%
}
```

However, this does not succeed. 

![grabbed_20161222-230835](https://cloud.githubusercontent.com/assets/1366654/21442009/940bc95e-c89b-11e6-8d21-638d273e3a8f.png)

**Comment by sieversMartin** [comment]
When using the preferred way
``` latex
\author[Vorname1 Name1\and Vorname2 Name 2]{Vorname1
Nachname1\footnote{Einrichtung/Universität, Abteilung, Anschrift, Postleitzahl
Ort, \email{emailadresse@author1}}\and Vorname2
Nachname2\footnote{Einrichtung/Universität, Abteilung, Anschrift, Postleitzahl
Ort, \email{emailadresse@author2}}
```

I have no problems.

**Comment by koppor** [comment]
Same here. Thank you for the hint! Maybe a warning should be output? I
assume that an adaption of \author is too hard. - Even though I find it
nicer for the user...

Am 24.12.2016 11:00 schrieb "Martin Sievers" <notifications@github.com>:

**Comment by koppor** [comment]
The thing is that the short authors and the short title is also used for the running heads. However, I'd like to have a properly formatted authors and title (without linebreaks) in the PDF properties and TOC, but a short title and the short authors in the running head. Is that possible somehow?
