### ISSUE TITLE
Enable starting at even page number

### ISSUE THREAD

**Issue by koppor** [sieversMartin/LNI#12]
When compiling proceedings, some papers start at on an even page. 

The title page does not take the `@editor`.

Patch:

Add
```
   \fancyhead[LE]{\small\@editor~(Hrsg.):\ \@booktitle,\linebreak\hspace{0.05cm}\thepage\hspace{5pt} Lecture Notes in Informatics (LNI), Gesellschaft für Informatik, Bonn~\@year}
```

## hyperref config

The page numbers are displayed correctly in the page counter, however the pages are swapped:

![grabbed_20161220-154837](https://cloud.githubusercontent.com/assets/1366654/21354825/c89a818c-c6cb-11e6-9833-2a8d8e1d9db9.png)

Is it really necessary to pass the options `TwoPageRight`/`TwoPageLeft` based on odd/even number of start page? Maybe, this is related to the headings issue and automatically be solved if that is solved?

**Comment by koppor** [comment]
hyperref seems to be difficult.

`AtBeginDocument` did not work out.

```
\RequirePackage{ifthen}
\AtBeginDocument{%
\ifthenelse{\isodd{\thepage}}%
  {\hypersetup{pdfpagelayout=TwoPageRight}}
  {\hypersetup{pdfpagelayout=TwoPageLeft}}
}
```

I think, one needs to introduce a class parameter containing the start page number.

**Comment by sieversMartin** [comment]
Isn't that part of the editorial process? Of course giving a starting page number is no magic at all. I will consider adding that. AFAIR it is/was part of the old template.

**Comment by koppor** [comment]
Sure. I am using the template for the editorial process.

Giving a starting page number did not work on my system using the old template. Therefore, I am using the new one.

**Comment by sieversMartin** [comment]
Okay. I'll check.

**Comment by koppor** [comment]
I think, it is enough to add the fancyhead config and leave hyperref as is.

Reason: The "Herausgeberrichtlinien" (März 2015) state the following:

> Die Beiträge müssen jeweils auf einer rechten (also ungerade nummerierten) Seite beginnen. Das bedeutet, dass bei Bedarf Leerseiten ohne Kopfzeile eingefügt werden müssen um das zu gewährleisten

I think, this could change if the template supports starting on even pages 🌞 - Springer also makes proceedings without empty filler pages 🌲 🌲

**Comment by sieversMartin** [comment]
> The page numbers are displayed correctly in the page counter, however the pages are swapped:

Please note, that not all PDF viewer will understand that option. I have no problems with Adobe on Windows. However, I removed it for now.
