### ISSUE TITLE
Keywords should take a space

### ISSUE THREAD

**Issue by koppor** [sieversMartin/LNI#13]
Got:
![grabbed_20161222-130725](https://cloud.githubusercontent.com/assets/1366654/21425134/98592df2-c847-11e6-8f3c-364c4f816a27.png)

Expected:

![grabbed_20161222-130657](https://cloud.githubusercontent.com/assets/1366654/21425125/89ed5676-c847-11e6-8c29-9559d108bf65.png)

New code to achieve expected result:

```
\newenvironment{keywords}{\fontsize{9}{10}\selectfont
    \noindent{\bfseries Keywords:\ }}{}
```

**Comment by sieversMartin** [comment]
Please read my comment for #14

**Comment by sieversMartin** [comment]
I added the space.
