### ISSUE TITLE
Authors with multiple Affiliations

### ISSUE THREAD

**Issue by Murgeye** [sieversMartin/LNI#158]
Hi,

Currently, the author command does not work with multiple affiliations (at least no as far as I can tell).

The following code (my best guess at doing this): 
```
\author[1,2]{Vorname1 Nachname1}{vorname1.name1@affiliation1.de}{0000-0000-0000-0000}
\author[2]{Vorname2 Nachname2}{vorname2.name2@affiliation2.de}{0000-0000-0000-0000}
\author[1]{Vorname3 Nachname3}{vorname3.name3@affiliation1.de}{0000-0000-0000-0000}
\author[1]{Vorname4 Nachname4}{vorname4.name4@affiliation1.de}{0000-0000-0000-0000}%
\affil[1]{Universität\\Abteilung\\Straße\\Postleitzahl Ort\\Land}
\affil[2]{University\\Department\\Address\\Country}
```
makes the author's e-mail address and OrcID disappear.
![image](https://github.com/gi-ev/LNI/assets/16648242/26e03c6a-0acc-4fd8-9815-a35e9712c678)

Is there a workaround or do we have to restate affiliations?

**Comment by sieversMartin** [comment]
Thanks for the report. Due to the current implementation, the affiliation has to be a number.

I mark this as a feature request.

**Comment by Narratot** [comment]
This implementation does not work in my case, as the information of the last stated author are repeated instead of mentioning the information of every author.

**Comment by sieversMartin** [comment]
Thanks for your message. Could you please provide a minimal working example?

**Comment by sieversMartin** [comment]
Further work at #173

**Comment by Narratot** [comment]
> Further work at #173

Then it should be solved there. That was my problem (two authors with identical affiliations)
