### ISSUE TITLE
Remove \hoffset and \voffset

### ISSUE THREAD

**Issue by koppor** [sieversMartin/LNI#22]
According to [weinelt.de](http://www.weinelt.de/latex/hoffset.html) and a personal discussion of the author of [pdfpages](https://www.ctan.org/pkg/pdfpages), `\hoffset` and `\voffset` are intended to be used in print production after the typesetting.

lni.cls contains these two lines at the beginning:

```
\setlength{\hoffset}{-0,2cm}% correct left margin to 4.2cm
\setlength{\voffset}{2.60cm}% correct top margin to 5.25cm
```

Is it possible to get rid of them?

The Word template has top: 5,25cm, bottom: 5,25cm, left: 4,2cm, right: 4,2cm, but the pages in the template seem larger. I'll try to come up with other values later.

I assume that using the [geometry](https://www.ctan.org/pkg/geometry) package is the solution?

**Comment by sieversMartin** [comment]
Well, they come from the original and I as said before tried to be "conservative" at first. However, I agree with you and have no problem getting rid of them.
