### ISSUE TITLE
Commas should be used as separation of authors

### ISSUE THREAD

**Issue by koppor** [sieversMartin/LNI#8]
The template defines `\and` as separator, which is good

Desired output:
![grabbed_20161220-135623](https://cloud.githubusercontent.com/assets/1366654/21351298/1fa4d820-c6bc-11e6-80b2-2f625e76b68d.png)

This was achieved by Thomas Neumann\footnote{...}, \, Viktor Leis ... in the old template.

Rendered output with this template:
![grabbed_20161220-135710](https://cloud.githubusercontent.com/assets/1366654/21351320/37eb6566-c6bc-11e6-9d37-98672a31497c.png)

## Running heads

In the running heads, the authors appear as "Thomas Neumann and Viktor Leis and Alfons Kemper"

I think, it should be "Thomas Neumann, Viktor Leis, and Alfons Kemper" or even "Thomas Neumann, Viktor Leis, and Alfons Kemper"

In the Word template, there is only an example with two authors, separated by " and ".

In the case of LNCS, three authors are written using "Thomas Neumann et al."

**Comment by sieversMartin** [comment]
Thank you. I have to check it. Maybe `\def\and{\unskip\,}` should read `\def\and{\unskip,}`

**Comment by koppor** [comment]
`\def\and{\unskip,}`:
![grabbed_20161220-142833](https://cloud.githubusercontent.com/assets/1366654/21352168/9a853518-c6c0-11e6-90ee-e6f4fa67e939.png)

`\def\and{\unskip,\,\ }`:
![grabbed_20161220-142937](https://cloud.githubusercontent.com/assets/1366654/21352210/bf785e22-c6c0-11e6-827c-c19021c5b4c2.png)

`\def\and{\unskip\hspace{-.42em},\hspace{.6em}}`:
![grabbed_20161220-143337](https://cloud.githubusercontent.com/assets/1366654/21352319/4e04cacc-c6c1-11e6-9ff0-2169925063c8.png)

I'm moving forward with that definition.

I used the update at  `\def\@@author[#1]#2{\gdef\@shortauthor{{\let\footnote\@gobble\def\and{\unskip,\ }#1}}\gdef\@author{#2}}` and it works perfectly at the running head:
![grabbed_20161220-143044](https://cloud.githubusercontent.com/assets/1366654/21352242/e725c108-c6c0-11e6-9cef-0a7d0807d2c6.png)

**Comment by koppor** [comment]
The only issue left is that it is not easily possible to provide the runningauthors:

![grabbed_20170106-002519](https://cloud.githubusercontent.com/assets/1366654/21701581/a7283dcc-d3a6-11e6-9a7c-38e97c9861e7.png)

My aim is to have `\authors[allauthornames separated by \and]{all authors with affilitations}` to be able to extract all author names for the TOC.

Quick fix - manually set fancyhead:

    \fancyhead[LE]{\hspace{0.05cm}\small\thepage\hspace{5pt}Christoph Pinkel et al.}

**Comment by sieversMartin** [comment]
I changed the file accordingly. However, I think the last point remains open for now.

**Comment by koppor** [comment]
I will close the issue and open a new one since https://github.com/sieversMartin/LNI/issues/8#issuecomment-270788587 is really a separate issue.
