### ISSUE TITLE
Enumartions are not rendered correctly

### ISSUE THREAD

**Issue by koppor** [sieversMartin/LNI#9]
Desired output:

![grabbed_20161220-140433](https://cloud.githubusercontent.com/assets/1366654/21351533/4014155c-c6bd-11e6-87cc-e516f0e540da.png)

(Maybe with nicer spacing of the dots. This looks very much like Microsoft Word)

Retrieved output:

![grabbed_20161220-140514](https://cloud.githubusercontent.com/assets/1366654/21351552/56bb126a-c6bd-11e6-9c9d-fde23d977d65.png)

**Comment by sieversMartin** [comment]
You mean `itemize`? Well, they are changed on purpose I guess. From the old documentation:
```
The \lni{} class redefines the standard lists environments \env{itemize} and 
% \env{enumerate} to meet the requirements of the \LNI{}.
```

**Comment by koppor** [comment]
Yes, I mean that. 😇 

In the two templates, I use following latex snippet:

```
\begin{itemize}
\item Word1
\item Word2
\end{itemize}
```

![grabbed_20161220-142330](https://cloud.githubusercontent.com/assets/1366654/21352033/f351eb7e-c6bf-11e6-9a2e-f6a36b500315.png)

**Comment by koppor** [comment]
Solved locally by using `\renewcommand\labelitemi{$\bullet$}`

**Comment by sieversMartin** [comment]
Well, the original definition is `\textbullet` which I leave for now.

**Comment by koppor** [comment]
I also saw that. However, if I compile the above tex snippet in the "original" template and in the new version, these two different outputs are created. Or am I wrong? I just compiled version 0.5 by Judith Michael (2014-12-18 11:55:00).

![grabbed_20170329-222658](https://cloud.githubusercontent.com/assets/1366654/24475003/db7504ca-14ce-11e7-8412-92098563237b.png)

**Comment by sieversMartin** [comment]
Well, you are right. `\textbullet` somehow behaves differently, i.e. it is small than in the old template. I used your suggestion.
